# Generated by Django 5.0.1 on 2024-02-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=254)),
                ('longitude', models.FloatField(max_length=254)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(default=None, max_length=64)),
                ('name', models.CharField(default=None, max_length=64)),
                ('otc', models.CharField(default=None, max_length=64)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='N', max_length=1)),
                ('beauty_title', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('other_titles', models.CharField(max_length=254)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('level_spring', models.CharField(blank=True, max_length=64)),
                ('level_summer', models.CharField(blank=True, max_length=64)),
                ('level_autumn', models.CharField(blank=True, max_length=64)),
                ('level_winter', models.CharField(blank=True, max_length=64)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_main.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='app_main.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.post')),
            ],
        ),
    ]
